### ISSUE TITLE
Secret encoding option and otplib.js compatibility

### ISSUE THREAD

**Issue by andreibratuleanu21** [Daegalus/dart-otp#15] opened 2020-03-26 16:23 UTC
Hello,

I'm trying to set up a app that receives a secret from a Node.js server that is using [otplib](https://www.npmjs.com/package/otplib). On their docs, the secret is a "base32 encoded **hex** secret key".

My problem is that when I create a HOTP 
`OTP.generateHOTPCode(_secret, _counter, algorithm: Algorithm.SHA256)`
it generates a key, but it's different from the one on the server so it fails to verify it.

So I thought that maybe the secret is decoded differently on the 2 packages. How should I encode the secret on the server-side so that both packages produce the same output?

**Comment by Daegalus** [comment] 2020-03-26 18:50
I am going to need some more info to get a clearer picture. Anything from the Secret, Algorithm, Digest, the counter being off, or how we implement Base32 can cause this.

For the server:
What algorithm are you using (the default for HOTP in their docs is SHA1)?
Are you using a custom digest?
Are you using the default encoding of `ascii` per their docs?
Can you potentially get me the output of the secret in byte form (this is to check if our base32 implementations are different somehow)?

For dart-otp:
Is secret the same string as in the node.js server?
You can import the `base32` library and use `base32.decode()` to get the bytes of the secret. Are they the same as the servers?
Is the time on the server out of sync with the client? 
What value are you using for `_counter` ?

**Comment by andreibratuleanu21** [comment] 2020-03-27 09:46
Ok, sure.

First when registering for 2FA, I use their method of token generation with `authenticator.generateSecret()`, and save that in a secure storage on app. I use algorithm: `SHA256` and encoding: `hex`. I've also tried with `ascii`, `utf8` and `base64` but no luck.
No custom digest.
When checking the otp I apply the same options. I'm not sure, if I can send you a byte form of the secret, but the there is a `decode` method that basically exposes the base32 module. If i input a base32 key like`OBRWE5CEFNFWQQJRMZRGM4LZMZIGKKZU` I get a `70636274442b4b68413166626671796650652b34` hex string.

I've checked if secret is the same. Also checked the time, it's the same, but not sure about the timestaps (also tried TOTP, but that doesn't work either). Counter is a int type var with value of 1 on both server and app.

Anyway, I'll try to import the base32 lib in both apps and you suggested and I'll come back with an update.

**Comment by Daegalus** [comment] 2020-03-27 19:48
Ok, thank you for the info, since we can rule out the base32 decode, I will focus on the otp. The last edit helps. I will attempt to replicate this locally. Just give me a bit of time to setup a node project to test with.

**Comment by Daegalus** [comment] 2020-03-27 21:46
Ok, I think I found the problem, its related to converting the counter into a list of bytes for the HMAC library. Something is messed up there and causing problems. Currently added tests from the RFC data sets so that i can run tests and figure out how to get accurate results. Thanks for bringing this to my attention. I will try to get it working asap as this is a major bug.

**Comment by andreibratuleanu21** [comment] 2020-03-27 22:05
Thanks for maintaining this awesome lib!

**Comment by Daegalus** [comment] 2020-03-31 22:31
So it wasn't quite what I thought it was at first, but it definitely was in that area. Turns out I wasn't doing padding right for TOTP, and I am not supposed to bad for HOTP. Along with that, I found that `otplib` does not base32 decode for you if you use `hotp` directly. So you need to base32 decode yourself. Otherwise it takes the string, takes the ascii decimals for each letter, and uses that as the secret. I only support base32 as input, so you need to do a base32 decode of the secret before passing it into the `otplib` hotp stuff. I will have an example script I used for testing to show you what I mean.

I will be releasing version 2.1.0 shortly. It has all the fixes, all the tests, additional features, and some other stuff I have found.

Since the HOTP RFC does not have instructions or support SHA256 and SHA512, I have defaulted back to SHA1 for HOTP, as I have found out that libraries don't handle SHA256 and SHA512 the same way, since its unsupported. SHA256/512 were added in the TOTP RFC, and have instructions on how to do padding and truncating of the secret to make it fit the 20, 32, and 64 byte requirements of the 3 supported hashes (SHA1, SHA256, and SHA512). In the TOTP RFC, SHA256 is the default, but in HOTP, SHA1 is.

I found other libraries (primarily otblib and speakeasy) don't do the padding for HOTP if you use the non-default hashes, so you get weird results. I made mine match otplib and speakeasy, but also added an option if you want to use TOTP style secret padding with HOTP, but remember compatibility might be a problem between languages and different libraries. My recommendation is to switch to TOTP, or use SHA1 for HOTP (though my codes for HOTP do match otplib and speakeasy when using sha256 and sha512 now)

As for the node.js script I used for testing, that is here:
```javascript
const otplib = require('otplib')
const speakeasy = require('speakeasy')
const base32 = require('thirty-two')

const hotp = otplib.hotp
 
const secret = 'OBRWE5CEFNFWQQJRMZRGM4LZMZIGKKZU';
const counter = 1

hotp.options = { algorithm: 'sha256', encoding: 'ascii'}
// Alternative:
// const secret = hotp.generateSecret();
// Note: .generateSecret() is only available for hotp and not totp/hotp
 
var tokense = speakeasy.hotp({
  secret: secret,
  encoding: 'base32',
  counter: counter,
  algorithm: 'sha256'
});

const token = hotp.generate(base32.decode(secret), counter);
console.log(token)
console.log(tokense)
```

Hopefully that shows you what I meant about base32. otplib only does base32 decode if you use their `authenticator` methods, which are TOTP.

Anyways. Thank you for all this, you still found some bugs, and I will be releasing 2.1.0 once I update documentation, readmes, and analyzer/formatting stuff.

**Comment by Daegalus** [comment] 2020-04-01 17:22
2.1.0 released, I am closing this for now. If the issue isn't resolved, please reopen.

**Closed by Daegalus** 2020-04-01 17:22 UTC
Labels: bug
