### ISSUE TITLE
Generated TOTP Code Sometimes Has Incorrect Length

### ISSUE THREAD

**Issue by abogdanovich1** [Daegalus/dart-otp#12] opened 2019-09-26 05:16 UTC
I've noticed that from time to time, the generated TOTP code length doesn't match the input I provide to the generator.

For example: I have a URL that has a length parameter of 8 digits. Most of the time it displays the correct 8 digits, but sometimes it'll display 6 or 7 digits.

<img width="211" alt="Screen Shot 2019-09-25 at 10 14 06 PM" src="https://user-images.githubusercontent.com/21229169/65659870-d70b7a00-dfe1-11e9-9f3c-0b62a98adc29.png">

Have not been able to narrow down what's causing this so far, but it tends to happen more often at the beginning of an app launch, rather than later on. 

Here's the URL I used to generate the codes in the screenshot: 
otpauth://totp/fake%40fake.com?secret=asdfasdfasdfasdf&issuer=Google&algorithm=SHA1&digits=8&period=20

**Comment by abogdanovich1** [comment] 2019-09-26 05:20
Actually, just read one of the closed issues from the project. When the int is generated, I simply copy the .toString() value and use that as the code.

I assume the issue is likely from the leading 0s being cut off during the conversion. If that is the case, and there isn't a bug here, just close this issue and excuse my ignorance :)

**Comment by Daegalus** [comment] 2019-09-26 23:24
Yes since it's an int, a 0 in the front is ignored. You can use string formattig to get that 0 there or check the length and pad left some 0s to the string.

I plan to add some more functions in the next update that will return a string instead of a int for these cases and some formatting functions.

I will close this since we figured out the cause and I will add some helper.methofs in the future.

**Closed by Daegalus** 2019-09-26 23:24 UTC
